name: mars
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  web_socket_channel: any #webSocket
  flutter_staggered_animations: ^0.1.2 #列表动画
  flutter_easyrefresh: ^2.0.8 # 刷新
  azlistview: ^1.0.1 #列表索引
  fl_chart: any
  webview_flutter_plus: any
  webview_flutter: any
  encrypt: any #加密
  dart_ipify: ^1.0.2 #获取ip
  audioplayer: ^0.8.1 #播放mp3
  flutter_pickers: ^1.0.1
  crypto: any
  flutter_datetime_picker: ^1.5.1
  cupertino_icons: ^1.0.2 #通用icon
  shared_preferences: ^2.0.10 #存储shared数据
  dio: ^4.0.4 #网络框架
  fluttertoast: ^7.1.6 #Toast提示
  fluro: ^2.0.3 #路由管理
  flutter_screenutil: 4.0.3+3 #屏幕适配方案
  flutter_swiper: ^1.1.6 #Banner
  cached_network_image: ^3.2.2 #加载网络
  pull_to_refresh: any #上拉下拉加载
  url_launcher: ^6.1.10 #调用系统外部
  install_plugin: ^2.0.1 #安装app
  permission_handler: ^10.2.0 #权限管理
  cookie_jar: ^3.0.1 #cookie
  dio_cookie_manager: ^2.0.0 #cookie
  waterfall_flow: ^2.0.5 #瀑布流
  flutter_inappwebview: ^5.4.3+7 #加载web
  package_info: ^2.0.0 #获取APP版本号
  qr_flutter: any # 生成二维码
  flutter_qr_reader: any #识别二维码
  image_gallery_saver: ^1.6.8 #保存图片
  provider: ^6.0.0 #状态管理
  path_provider: any #获取系统目录
  flutter_keyboard_visibility: ^5.3.0  #监听软键盘
  flutter_html: any #加载Html元素
  city_pickers: ^1.0.1 #中国的城市三级联动选择器
  event_bus: ^2.0.0 #全局传值
  image_picker: ^0.8.4+4 #拍照和相册选择照片
  image_cropper: ^2.0.3 #图片裁剪
  multi_image_picker2: ^5.0.2
  percent_indicator: ^4.0.0 #进度条
  barcode_scan2: ^4.2.1 #扫二维码
  json_annotation: any #JSON
  json_serializable: any
  build_runner: any
  flutter_slidable: ^1.3.0 #侧滑删除
  dotted_border: ^2.0.0 #虚线边框
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_thunk: ^0.4.0
  transparent_pointer: ^1.0.0
  intl: ^0.17.0
  ffi: any
  device_info_plus: ^4.0.0
  image_fade: ^0.6.1
#  walletconnect_qrcode_modal_dart: ^0.3.0
#  walletconnect_dart: ^0.0.11
#  algorand_dart: ^1.0.3
#  wallet_connect: ^1.0.4
  walletconnect_flutter_v2: ^1.1.4
  eth_sig_util: ^0.0.9
  walletconnect_dart: ^0.0.11

#  qr_code_scanner: ^0.7.0
#  socket_io_client: ^1.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/wallet/

flutter_intl:
  enabled: true
